#!/bin/bash

sudo apt update -y && sudo apt upgrade -y && \
sudo apt install zsh git && \
curl https://raw.githubusercontent.com/manasm11/my_zshrc/master/.zshrc --output ~/.zshrc && \
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k && \
echo "" >>  ~/.bashrc && \
echo zsh >> ~/.bashrc

